
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-boot'
    metrics_path: '/actuator/prometheus'
    static_configs:

      - targets: ['wiki-backend:8080']
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
