server:
  port: 8080

# релизный конфиг

spring:
  application:
    name: WikiBackend
  security:
    user:
      name: admin
      password: Admin@123

  data:
    mongodb:
      host: 213.171.12.202
      port: 27017
      database: wikicontent
      username: altauser
      password: AltaUser24_
      authenticationDatabase: admin


  datasource:
    url: jdbc:postgresql://194.135.36.133:5432/wikidb
    username: altauser
    password: altauser
    driver-class-name: org.postgresql.Driver
#    hikari:
#      schema: alt_11


  jpa:
    properties:
      hibernate:
        multiTenancy: SCHEMA
#        multi_tenant_connection_provider: com.example.wikibackend.config.TenantConnectionProvider
#        tenant_identifier_resolver: com.example.wikibackend.config.TenantIdentifierResolver
        schema_management_tool:
          coordination: none
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
        ddl-auto: none
        temp:
          use_jdbc_metadata_defaults: false
    generate-ddl: true


springdoc:
  swagger-ui:
    enabled: true
    url: /v3/api-docs
    tagsSorter: alpha
    path: /swagger-ui
  api-docs:
    enabled: true
    path: /v3/api-docs

logging:
  level:
    org:
      springframework: INFO
      hibernate: INFO
    com:
      example:
        wikibackend:
          config: INFO

    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"
jwt:
  secret: my-super-secret-key-for-jwt-signature
  expiration:
    access: 3600000  # 1 час в миллисекундах
    refresh: 86400000 # 1 день в миллисекундах