spring:
  application:
    name: WikiBackend

  data:
    mongodb:
      host: localhost
      port: 27017
      database: wikicontent

  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/wikidb
    username: postgres
    password: postgres
  #    hikari:
  #      #      schema: news
  #      #      connection-ini-sql: CREATE SCHEMA IF NOT EXISTS news
  #      connection-timeout: 10000

  jpa:
    properties:
      hibernate:
        multiTenancy: SCHEMA
        schema_management_tool:
          coordination: none
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        ddl-auto: update
        temp:
          use_jdbc_metadata_defaults: false
    generate-ddl: true


springdoc:
  swagger-ui:
    enabled: true
    tagsSorter: alpha
  api-docs:
    enabled: true
#  openapi:
#    version: 3.0.3

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"