spring:
  application:
    name: WikiBackend

  data:
    mongodb:
      host: 213.171.12.202
      port: 27017
      database: wikicontent

  datasource:
    url: jdbc:postgresql://194.135.36.133:5432/wikidb
    username: altauser
    password: altauser
#    hikari:
#      #      schema: news
#      #      connection-ini-sql: CREATE SCHEMA IF NOT EXISTS news
#      connection-timeout: 10000

  jpa:
    properties:
      hibernate:
        multiTenancy: SCHEMA
        schema_management_tool:
          coordination: none
#        tenant_identifier_resolver: com.example.wikibackend.config.TenantIdentifierResolverImpl
#        multi_tenant_connection_provider: com.example.wikibackend.config.MultiTenantConnectionProviderImpl
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        ddl-auto: none
        temp:
          use_jdbc_metadata_defaults: false
    generate-ddl: true


springdoc:
  swagger-ui:
    tagsSorter: alpha

