server:
  port: 8080

# релизный конфиг

spring:
  application:
    name: WikiBackend
  security:
    user:
      name: admin
      password: Admin@123

  data:
    mongodb:
      host: 213.171.12.202
      port: 27017
      database: wikicontent
      username: altauser
      password: AltaUser24_
      authenticationDatabase: admin


  datasource:
    url: jdbc:postgresql://194.135.36.133:5432/wikidb
    username: altauser
    password: altauser
#    hikari:
#      #      schema: news
#      #      connection-ini-sql: CREATE SCHEMA IF NOT EXISTS news
#      connection-timeout: 10000

  jpa:
    properties:
      hibernate:
        multiTenancy: SCHEMA
        schema_management_tool:
          coordination: none
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        ddl-auto: update
        temp:
          use_jdbc_metadata_defaults: false
    generate-ddl: true


springdoc:
  swagger-ui:
    enabled: true
    url: /v3/api-docs
    tagsSorter: alpha
    path: /swagger-ui
  api-docs:
    enabled: true
    path: /v3/api-docs

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"